JenkinsFile

diff --git a/spring-boot-app/JenkinsFile b/spring-boot-app/JenkinsFile
--- a/spring-boot-app/JenkinsFile
+++ b/spring-boot-app/JenkinsFile
@@ -85,4 +85,16 @@ pipeline {
 
                             if [ -f "spring-boot-app-manifests/deployment.yml" ]; then
                                 sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-app-manifests/deployment.yml
-                                git add spring-boot-app-manifests/deplo
+                                git add spring-boot-app-manifests/deployment.yml
+                                git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                                git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:refs/heads/master
+                            else
+                                echo "❌ Error: Deployment file not found!" && exit 1
+                            fi
+                        '''
+                    }
+                }
+            }
+        }
+    } // Closing 'stages'
+} // Closing 'pipeline'
